project:
  type: website
  output-dir: docs

website:
  title: "Gracia Larsen-Schmidt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: mp_1.qmd
        text: Mapping C-Sections
      - href: mp_4.qmd
        text: Textual Analysis, Quran & Bible

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    page-layout: full

editor: visual

