project:
  type: website
  output-dir: docs

website:
  title: "Gracia Larsen-Schmidt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - mp_1.qmd
      - mp_2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

